cache:
  paths:
  - node_modules/

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - git submodule update --remote --init

部署到杭州办公测试环境:
  script:
    - cd fed-docs
    - ls
    # - git submodule update --remote --init --recursive
    # - npm install --registry=https://registry.npm.taobao.org
    # - cp hekr-h5-sdk/README.md docs/hekr-h5-sdk.md
    # - cp hekr-cli/README.md docs/hekr-cli.md
    # - cp virtual/README.md docs/virtual.md
    # - npm run build
    # - rm -rf `ls /data/www/fed-docs/ | egrep -v '(hekr-components|auto)' | sed 's:^:/data/www/fed-docs/:'`
    # - cp -R docs/.vuepress/dist/* /data/www/fed-docs/
  tags:
    - hz-test
  only:
    - master
  when: always
  environment:
    name: 10.10.1.2
    url: http://10.10.1.2:7777/
