部署文档:
  script:
    - npm install --registry=https://registry.npm.taobao.org
    - npm run docs:build
    - rm -rf /home/diao.cheng/fed-docs/hekr-component/*
    - cp -R docs/* /home/diao.cheng/fed-docs/hekr-component/
  tags:
    - hz-test
  only:
    - master
  when: always
  environment:
    name: 10.10.1.3
    url: http://10.10.1.3:7777/
