部署文档:
  script:
    - npm install --registry=https://registry.npm.taobao.org
    - npm run docs:build
    - rm -rf `ls -a /home/diao.cheng/fed-docs/ | egrep -v '(hekr-cli|hekr-h5-sdk|hekr-components|auto)'`
    - cp -R dist/* /home/diao.cheng/fed-docs/
  tags:
    - hz-test
  only:
    - master
  when: always
  environment:
    name: 10.10.1.3
    url: http://10.10.1.3:7777/
