部署到杭州办公测试环境:
  script:
    - npm install --registry=https://registry.npm.taobao.org
    - npm run build
    - rm -rf `ls /data/www/fed-docs/fed-docs/ | egrep -v '(hekr-components|auto)' | sed 's:^:/data/www/fed-docs/:'`
    - cp -R docs/.vuepress/dist/* /data/www/fed-docs/
  tags:
    - hz-test
  only:
    - master
  when: always
  environment:
    name: 10.10.1.2
    url: http://10.10.1.2:7777/
